//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELEKTRIK.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABONE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ABONE()
        {
            this.SAYAC = new HashSet<SAYAC>();
        }
    
        public int ABONEID { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string TCKIMLIK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAYAC> SAYAC { get; set; }
    }
}
