//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELEKTRIK.ENTITY
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ELEKTRIKEntities : DbContext
    {
        public ELEKTRIKEntities()
            : base("name=ELEKTRIKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ABONE> ABONE { get; set; }
        public virtual DbSet<SAYAC> SAYAC { get; set; }
        public virtual DbSet<TUKETIM> TUKETIM { get; set; }
    
        public virtual ObjectResult<spAboneDoldur_Result> spAboneDoldur()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spAboneDoldur_Result>("spAboneDoldur");
        }
    
        public virtual int spAboneKaydet(string aD, string sOYAD, string tC, string mARKA, string sERI, string nUMARA)
        {
            var aDParameter = aD != null ?
                new ObjectParameter("AD", aD) :
                new ObjectParameter("AD", typeof(string));
    
            var sOYADParameter = sOYAD != null ?
                new ObjectParameter("SOYAD", sOYAD) :
                new ObjectParameter("SOYAD", typeof(string));
    
            var tCParameter = tC != null ?
                new ObjectParameter("TC", tC) :
                new ObjectParameter("TC", typeof(string));
    
            var mARKAParameter = mARKA != null ?
                new ObjectParameter("MARKA", mARKA) :
                new ObjectParameter("MARKA", typeof(string));
    
            var sERIParameter = sERI != null ?
                new ObjectParameter("SERI", sERI) :
                new ObjectParameter("SERI", typeof(string));
    
            var nUMARAParameter = nUMARA != null ?
                new ObjectParameter("NUMARA", nUMARA) :
                new ObjectParameter("NUMARA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAboneKaydet", aDParameter, sOYADParameter, tCParameter, mARKAParameter, sERIParameter, nUMARAParameter);
        }
    
        public virtual ObjectResult<spTuketimDoldur_Result> spTuketimDoldur(Nullable<int> aBONENO)
        {
            var aBONENOParameter = aBONENO.HasValue ?
                new ObjectParameter("ABONENO", aBONENO) :
                new ObjectParameter("ABONENO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spTuketimDoldur_Result>("spTuketimDoldur", aBONENOParameter);
        }
    
        public virtual int spTuketimEkle(Nullable<int> eNDEKS, Nullable<int> sAYACNO)
        {
            var eNDEKSParameter = eNDEKS.HasValue ?
                new ObjectParameter("ENDEKS", eNDEKS) :
                new ObjectParameter("ENDEKS", typeof(int));
    
            var sAYACNOParameter = sAYACNO.HasValue ?
                new ObjectParameter("SAYACNO", sAYACNO) :
                new ObjectParameter("SAYACNO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spTuketimEkle", eNDEKSParameter, sAYACNOParameter);
        }
    
        public virtual int spTuketimHesapla()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spTuketimHesapla");
        }
    
        public virtual ObjectResult<spAboneAra_Result> spAboneAra(string kelime)
        {
            var kelimeParameter = kelime != null ?
                new ObjectParameter("Kelime", kelime) :
                new ObjectParameter("Kelime", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spAboneAra_Result>("spAboneAra", kelimeParameter);
        }
    }
}
