//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELEKTRIK.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAYAC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SAYAC()
        {
            this.TUKETIM = new HashSet<TUKETIM>();
        }
    
        public int SAYACID { get; set; }
        public Nullable<int> ABONENO { get; set; }
        public string MARKA { get; set; }
        public string SERI { get; set; }
        public string NUMARA { get; set; }
    
        public virtual ABONE ABONE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TUKETIM> TUKETIM { get; set; }
    }
}
