//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELEKTRIK.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUKETIM
    {
        public int TUKETIMID { get; set; }
        public Nullable<int> SAYACNO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<int> ENDEKS { get; set; }
        public Nullable<int> TUKETIM1 { get; set; }
    
        public virtual SAYAC SAYAC { get; set; }
    }
}
